# .prettierrc.toml

bracketSpacing = true
insertPragma = false
jsxBracketSameLine = false
printWidth = 85
proseWrap = "always"
requirePragma = false
semi = true
singleQuote = true
tabWidth = 2
trailingComma = "all"
softWrap = true

[[overrides]]
files = ["*.ts", "*.js", "*.tsx", "*.jsx", "*.json", "*.json5"]
[overrides.options]
printWidth = 85
tabWidth = 2

[[overrides]]
files = "*.md"
[overrides.options]
proseWrap = "preserve"
